# Generated by Django 5.1.1 on 2024-10-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_local_owner_category_local_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='local_owner_id',
            new_name='local_owner',
        ),
    ]
