# Generated by Django 5.1.1 on 2024-10-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_available_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available_time_range',
        ),
        migrations.RemoveField(
            model_name='products',
            name='available_time_range',
        ),
        migrations.AddField(
            model_name='category',
            name='available_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='available_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='available_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='available_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
